Repository ros-infrastructure/bloom, pull requests merged in 2021-02, with the labels that each got.

#613 Fix some syntax warnings with literal comparisons
  test/utils/common.py
Labels: bug

#612 Add a template substitution for the ROS distro
  bloom/generators/rosdebian.py
  bloom/generators/rosrpm.py
Labels: enhancement

#607 update email addresses and remove 404 download url
  setup.py
Labels: documentation
